global FALSIF_EXP_FILE_NAME

BASE_EXP_DATA_FOLDER = 'D:\TEST_RESULTS_FOLDER\TRAJ_LOGS\iv2018_exp1\';
CA_TRAJ_FILES_PREFIX = [BASE_EXP_DATA_FOLDER, 'Covering_Array\iv2018_exp1_CA_trajectory_'];
GLOBAL_UR_TRAJ_FILES_PREFIX = [BASE_EXP_DATA_FOLDER, 'Global_UR\iv2018_exp1_Global_UR_'];
WORST_FALSIFICATION_SA_TRAJ_FILES_PREFIX = [BASE_EXP_DATA_FOLDER, 'Worst_Case_Falsification\fals_SA_'];
WORST_FALSIFICATION_UR_TRAJ_FILES_PREFIX = [BASE_EXP_DATA_FOLDER, 'Worst_Case_Falsification\fals_UR_'];
ZERO_FALSIFICATION_SA_TRAJ_FILES_PREFIX = [BASE_EXP_DATA_FOLDER, 'Zero_Robustness_Falsification\fals_SA_'];
ZERO_FALSIFICATION_UR_TRAJ_FILES_PREFIX = [BASE_EXP_DATA_FOLDER, 'Zero_Robustness_Falsification\fals_UR_'];

FALSIF_EXP_FILE_NAME = 'D:\PerceptionVnV\tests\iv2018_exp1\exp_config\straight_road_pedestrian_jump_ca_2_way.csv';
FALSIF_EXP_RESULTS_FILE_PREFIX = [BASE_EXP_DATA_FOLDER, 'Matlab_exp_results\Falsification_'];
MATLAB_LOGS_FOLDER = [BASE_EXP_DATA_FOLDER, 'Matlab_logs\'];

