run_falsification_after_ca_scenario_1_r2
run_falsification_after_ca_scenario_1_r4
run_falsification_after_ca_scenario_1_r1
% We don't have Scenario 1 R3 in the paper:
% run_falsification_after_ca_scenario_1_r3